namespace SingleplayerLauncher.Names
{
    public static class Trait
    {
        public const string
            EASILY_EXCITED = "Easily Excited",
            MAKING_IT_RAIN = "Making it Rain",
            NATURAL_BORN_SPRINTER = "Natural Born Sprinter",
            KIDNAPPED_A_LEPRECHAUN = "Kidnapped a Leprechaun",
            OVER_REACTING = "Over-Reacting",
            AVOIDS_PAIN = "Avoids Pain",
            FIRE_SALE = "Fire Sale",
            ICE_COLD_DEALS = "Ice Cold Deals",
            INSANE_ARCANE_SALE = "Insane Arcane Sale",
            LIGHTNING_DEALS = "Lightning Deals",
            BIG_SPENDER = "Big Spender",
            NEVER_PAYS_RETAIL = "Never Pays Retail",
            ONE_WITH_THE_TRAPS = "One with the Traps",
            OVERACHIEVER = "Overachiever",
            OVERPROTECTIVE = "Overprotective",
            RIFT_GIFT = "Rift Gift",
            RIFT_ROCKET = "Rift Rocket",
            SMASHING_DEALS = "Smashing Deals",
            HAS_A_TRAP_FETISH = "Has a Trap Fetish",
            BELIEVES_SIZE_MATTERS = "Believes Size Matters",
            UNCLE_KILLED_BY_GIANT = "Uncle Killed by Giant",
            CAT_EATEN_BY_GNOLLS = "Cat Eaten by Gnolls",
            BROTHER_MAULED_BY_GRIZZLIES = "Brother Mauled by Grizzlies",
            SISTER_EATEN_BY_AN_OGRE = "Sister Eaten by an Ogre",
            DOG_KILLED_BY_PRIDE_HUNTERS = "Dog Killed by Pride Hunters",
            GRANDMOTHER_EATEN_BY_A_TROLL = "Grandmother Eaten by a Troll",
            DIFFICULTY_CALMING_DOWN = "Difficulty Calming Down",
            AMATEUR_VETERINARIAN = "Amateur Veterinarian",
            SOLDIERS_TOOK_MY_HORSE = "Soldiers Took My Horse",
            HAS_ULTIMATE_SET_OF_TOOLS = "Has Ultimate Set of Tools",
            BEAR_HUGS = "Bear Hugs",
            HAS_A_BIG_BROTHER = "Has a Big Brother",
            KILLER_BUZZ = "Killer Buzz",
            PAGING_DR_LOVE = "Paging Dr Love",
            RIFT_AWAY = "Rift Away",
            FEELING_FIERCE = "Feeling Fierce",
            TRIES_TOO_HARD = "Tries Too Hard",
            ENJOYS_PAIN = "Enjoys Pain",
            EXECUTION_ADVANTAGE = "Execution Advantage",
            FEELS_SAFE_AT_HOME = "Feels Safe at Home",
            PRACTICES_WITCHCRAFT = "Practices Witchcraft",
            HIGH_PAIN_TOLERANCE = "High Pain Tolerance",
            WALKS_IT_OFF = "Walks It Off",
            TAKES_LESSONS_FROM_CYGNUS = "Takes Lessons from Cygnus",
            WALL_BUILDING_PHD = "Wall Building PhD",
            ATTENTION_DEFICIT = "Attention Deficit",
            EXTRA_PADDING = "Extra Padding",
            RESPECT_MY_AUTHORITY = "Respect My Authority";
    }
}
