namespace SingleplayerLauncher.Names
{
    public static class Trait
    {
        public const string
            EASILY_EXCITED = "Easily Excited",
            MAKING_IT_RAIN = "Making it Rain",
            NATURAL_BORN_SPRINTER = "Natural Born Sprinter",
            KIDNAPPED_A_LEPRECHAUN = "Kidnapped a Leprechaun",
            OVER_REACTING = "Over-Reacting",
            AVOIDS_PAIN = "Avoids Pain",
            FIRE_SALE = "Fire Sale",
            ICE_COLD_DEALS = "Ice Cold Deals",
            INSANE_ARCANE_SALE = "Insane Arcane Sale",
            LIGHTNING_DEALS = "Lightning Deals",
            BIG_SPENDER = "Big Spender",
            NEVER_PAYS_RETAIL = "Never Pays Retail",
            ONE_WITH_THE_TRAPS = "One with the Traps",
            OVERACHIEVER = "Overachiever",
            OVERPROTECTIVE = "Overprotective",
            RIFT_GIFT = "Rift Gift",
            RIFT_ROCKET = "Rift Rocket",
            SMASHING_DEALS = "Smashing Deals",
            HAS_A_TRAP_FETISH = "Has a Trap Fetish",
            BELIEVES_SIZE_MATTERS = "Believes Size Matters",
            UNCLE_KILLED_BY_GIANT = "Uncle Killed by Giant",
            CAT_EATEN_BY_GNOLLS = "Cat Eaten by Gnolls",
            BROTHER_MAULED_BY_GRIZZLIES = "Brother Mauled by Grizzlies",
            SISTER_EATEN_BY_AN_OGRE = "Sister Eaten by an Ogre",
            DOG_KILLED_BY_PRIDE_HUNTERS = "Dog Killed by Pride Hunters",
            GRANDMOTHER_EATEN_BY_A_TROLL = "Grandmother Eaten by a Troll",
            DIFFICULTY_CALMING_DOWN = "Difficulty Calming Down",
            AMATEUR_VETERINARIAN = "Amateur Veterinarian",
            SOLDIERS_TOOK_MY_HORSE = "Soldiers Took My Horse",
            HAS_ULTIMATE_SET_OF_TOOLS = "Has Ultimate Set of Tools",
            BEAR_HUGS = "Bear Hugs",
            HAS_A_BIG_BROTHER = "Has a Big Brother",
            KILLER_BUZZ = "Killer Buzz",
            PAGING_DR_LOVE = "Paging Dr Love",
            RIFT_AWAY = "Rift Away",
            FEELING_FIERCE = "Feeling Fierce",
            TRIES_TOO_HARD = "Tries Too Hard",
            ENJOYS_PAIN = "Enjoys Pain",
            EXECUTION_ADVANTAGE = "Execution Advantage",
            FEELS_SAFE_AT_HOME = "Feels Safe at Home",
            PRACTICES_WITCHCRAFT = "Practices Witchcraft",
            HIGH_PAIN_TOLERANCE = "High Pain Tolerance",
            WALKS_IT_OFF = "Walks It Off",
            TAKES_LESSONS_FROM_CYGNUS = "Takes Lessons from Cygnus",
            WALL_BUILDING_PHD = "Wall Building PhD",
            ATTENTION_DEFICIT = "Attention Deficit",
            EXTRA_PADDING = "Extra Padding",

            // Siege Only
            RESPECT_MY_AUTHORITY = "Respect My Authority",
            CACHE_WHISPERER = "Cache Whisperer",
            NEEDS_ALONE_TIME = "Needs Alone Time",
            LARGE_AND_IN_CHARGE = "Large and in Charge",
            RANSACKING_OBSESSION = "Ransacking Obsession",
            BORN_LEADER = "Born Leader",
            OH_WOW_BANDAGES = "Oh, Wow! Bandages!",
            SELLS_MAGIC_TO_MAGES = "Sells Magic to Mages",
            WORKS_SMARTER = "Works Smarter",
            MOTIVATES_OTHERS = "Motivates Others",
            OH_WOW_POTIONS = "Oh, Wow! Potions!",
            LIKE_YOU_STOLE_IT = "Like You Stole It",
            DOESNT_PLAY_WELL_WITH_OTHERS = "Doesn't Play Well with Others",
            MOB_MENTALITY = "Mob Mentality",
            SETTING_AN_EXAMPLE = "Setting an Example",
            STRANGE_SENSE_OF_HUMOR = "Strange Sense of Humor",
            NEVER_KNOCKS = "Never Knocks",
            REALLY_COLD_HANDS = "Really Cold Hands",
            HAS_FIERY_RAGE = "Has Fiery Rage",
            RIP_THAT_SUCKER_OPEN = "Rip That Sucker Open",
            ITS_MINE = "It's Mine!",
            NOT_SCARED_OF_STATUES = "Not Scared of Statues",
            IM_NOT_TOUCHING_YOU = "I'm Not Touching You",
            GUARDIAN_VANDALISM = "Guardian Vandalism",
            IS_A_WALKING_PINCUSHION = "Is a Walking Pincushion";
    }
}
